# -*- coding: utf-8 -*-
"""Sistem Rekomendasi_Bela Ismawati Nuraisa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/belaismawati/sistem-rekomendasi-bela-ismawati-nuraisa.daff8be4-d389-420e-ac6c-1d80bad88c0b.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251229/auto/storage/goog4_request%26X-Goog-Date%3D20251229T160536Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D71802f16a632f691bbe3527e0aea528e39a99fb309e9c3356996269dffa54580c5a87ce60840dd9ba5ba9491e450d44a26b626a2e6be3d92588e6f0d7bc2e9ce951935023a8dec361c74a9f696b2bf4a1115bea3729f05df89c82fadef95a76abe6199174ee7bf974808be3e3739371757a1ab48a8654a5dca199d565ee6ad9204088b6204d7afff157c8a681fd5fbd0890e02d3b3dd968e278b2b3626f3ce46ab0968885fd10f094bc4521d9bf96db85432f01b3da7fb06ac9b80690a85052fd8950eed9e4b9f510ed4a28c4fc6e468ade074c26aeb65a76d8e397c7e21c752da11cf5cbf67093f1194def452693f0e26e4772d108851affddc6d69c4a4f3dd

## **Import Library**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

"""## **Data Understanding**"""

# Unzip file
# !unzip /kaggle/input/book-recomendation-dataset

# Membaca Dataset ke dalam DataFrame Pandas
books = pd.read_csv('/kaggle/input/book-recomendation-dataset/Books.csv')
ratings = pd.read_csv('/kaggle/input/book-recomendation-dataset/Ratings.csv')
users = pd.read_csv('/kaggle/input/book-recomendation-dataset/Users.csv')

print('Jumlah data buku: ', len(books.ISBN.unique()))
print('Jumlah data penilaian buku: ', len(ratings.ISBN.unique()))
print('Jumlah data penilaian yang diberikan pengguna: ', len(ratings['User-ID'].unique()))
print('Jumlah data profil pengguna: ', len(users['User-ID'].unique()))

"""## **Univariate Exploratory Data Analysis**

Ringkasan *Book Recomendation Dataset* :

1. **books:**
    * Berisi informasi mengenai buku yang diidentifikasi berdasarkan **ISBN**-nya.
    * Tersedia informasi berbasis konten: **judul**, **penulis** (hanya penulis pertama), **tahun terbit**, dan **penerbit buku** yang diperoleh dari Amazon.
    * Tersedia **URL gambar sampul** (terdiri dari 3 varian, yaitu Image-URL-S, Image-URL-M, Image-URL-L) yang mengarah ke Amazon.

2. **ratings:**
    * Berisi informasi mengenai **rating buku**.
    * Rating eksplisit ditunjukkan dengan **skala 1-10** (nilai yang lebih tinggi menunjukkan apresiasi yang lebih tinggi).
    * Rating implisit ditunjukkan dengan **angka 0** (menandakan interaksi tanpa penilaian eksplisit).

3. **users:**
    * Berisi data pengguna dengan **User-ID** yang telah dianonimkan dan dipetakan ke bilangan bulat.
    * Tersedia data demografis pengguna, seperti **Lokasi** dan **Usia**.

### **File Books**
"""

# Menghitung jumlah baris dan kolom dalam DataFrame
jumlah_baris_books, jumlah_kolom_books = books.shape

print("Jumlah baris:", jumlah_baris_books)
print("Jumlah kolom:", jumlah_kolom_books)

books.head()

"""Output kode di atas memberikan informasi sebagai berikut:

* Terdapat **271.360 baris** dalam dataset.
* Terdapat **8 kolom** dalam dataset, yang terdiri dari: **ISBN**, **Book-Title**, **Book-Author**, **Year-Of-Publication**, **Publisher**, **Image-URL-S**, **Image-URL-M**, dan **Image-URL-L**.
"""

# Mengubah nama kolom
books = books.rename(columns={
    'Book-Title': 'book_title',
    'Book-Author': 'book_author',
    'Year-Of-Publication': 'year',
    'Publisher': 'publisher',
    'Image-URL-S': 'image_url_s',
    'Image-URL-M': 'image_url_m',
    'Image-URL-L': 'image_url_l'
})
books.head()

# Melihat info file books
books.info()

"""Dari output di atas, diketahui bahwa **file books.csv** memiliki **kolom dengan tipe data object**."""

# Jumlah buku yang unik berdasarkan ISBN
print('Jumlah buku: ', len(books.ISBN.unique()))

# Jumlah judul buku
print('Jumlah judul buku: ', len(books.book_title.unique()))

# Jumlah penulis buku yang unik
print('Jumlah penulis buku: ', len(books.book_author.unique()))

# Jumlah penerbit
print('Jumlah penerbit: ', len(books.publisher.unique()))

"""Dari output di atas, diketahui bahwa:
* Jumlah buku yang unik berdasarkan ISBN adalah **271.360 buku**.
* Terdapat total **242.135 judul buku**.
* Jumlah penulis buku adalah **102.023 penulis**.
* Terdapat total **16.808 penerbit**.
"""

# Memeriksa duplikasi
print("Jumlah duplikasi pada books: ", books.duplicated().sum())

# Menghitung jumlah buku per penulis
author_counts = books['book_author'].value_counts().head(10)

# Visualisasi
plt.figure(figsize=(10,6))
sns.barplot(y=author_counts.index, x=author_counts.values)
plt.title('Distribusi Jumlah Buku per Penulis')
plt.xlabel('Jumlah Buku')
plt.ylabel('Penulis')
plt.show()

"""Dari output tersebut, diketahui bahwa Agatha Christie menempati posisi teratas sebagai penulis dengan jumlah buku terbanyak, yang kemudian diikuti oleh William Shakespeare, Stephen King, dsb."""

# Menghitung jumlah buku per penerbit
publisher_counts = books['publisher'].value_counts().head(10)

# Visualisasi
plt.figure(figsize=(10,6))
sns.barplot(y=publisher_counts.index, x=publisher_counts.values)
plt.title('Distribusi Jumlah Buku per Penerbit')
plt.xlabel('Jumlah Buku')
plt.ylabel('Penerbit')
plt.show()

"""Dari output tersebut, diketahui bahwa Harlequin menempati posisi teratas sebagai penerbit dengan jumlah buku terbanyak, jauh melampaui penerbit lainnya.

### **File Ratings**
"""

# Menghitung jumlah baris dan kolom dalam DataFrame
jumlah_baris_ratings, jumlah_kolom_ratings = ratings.shape

print("Jumlah baris:", jumlah_baris_ratings)
print("Jumlah kolom:", jumlah_kolom_ratings)

ratings.head()

"""Output kode di atas memberikan informasi sebagai berikut:

* Terdapat **1.149.780 baris** dalam dataset.
* Terdapat **3 kolom** dalam dataset, yang terdiri dari: **User-ID**, **ISBN**, dan **Book-Rating**.
"""

# Mengubah nama kolom
ratings = ratings.rename(columns={
    'User-ID': 'UserID',
    'Book-Rating': 'book_rating'
})
ratings.head()

# Melihat info file ratings
ratings.info()

"""Dari output di atas, diketahui bahwa:
* Terdapat kolom dengan **tipe data object**, yaitu **kolom ISBN**.
* Terdapat kolom numerik dengan **tipe data int64**, yaitu **kolom UserID** dan **book_rating**.
"""

# Melihat distribusi ratings
ratings.describe()

"""Dari output di atas, diketahui bahwa **nilai maksimum rating adalah 10** dan **nilai minimumnya adalah 0**. Tapi perlu diingat kembali, rating pada dataset ini dapat bersifat **eksplisit** (yang ditunjukkan dengan pemberian **nilai antara 1 sampai 10**) atau **implisit** (yang ditunjukkan dengan **nilai 0**).

Karena proyek ini akan berfokus pada Collaborative Filtering, maka rating yang digunakan adalah rating yang bersifat eksplisit. Sehingga rating yang bersifat implisit akan dihapus dari dataset.
"""

# Mengambil baris yang memiliki rating selain nilai 0
ratings = ratings[ratings['book_rating'] != 0]

# Melihat distribusi rating
ratings.describe()

# Jumlah buku yang unik berdasarkan ISBN
print('Jumlah buku: ', len(ratings.ISBN.unique()))

# Jumlah user
print('Jumlah user: ', len(ratings.UserID.unique()))

# Jumlah data rating
print('Jumlah rating: ', len(ratings.book_rating))

"""Dari output di atas, diketahui bahwa:
* Jumlah buku yang unik berdasarkan ISBN adalah **185.973 buku**.
* Terdapat total **77.805 user**.
* Terdapat total **433.671 rating**.
"""

# Memeriksa duplikasi
print("Jumlah duplikasi pada ratings: ", ratings.duplicated().sum())

plt.figure(figsize=(7,5))
ax = sns.countplot(x='book_rating', data=ratings)
plt.title('Distribusi Rating Buku')
plt.xlabel('Rating')
plt.ylabel('Jumlah')

# Menambahkan label jumlah di atas bar
for p in ax.patches:
    ax.annotate(str(int(p.get_height())),
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom')
plt.show()

"""Grafik ini menunjukkan jumlah rating yang diberikan oleh pengguna terhadap buku dalam skala 1 hingga 10. Dari grafik ini diperoleh beberapa poin:
* Terdapat 103.736 user yang memberikan rating 8, yang berarti mayoritas pengguna cenderung memberikan penilaian positif terhadap buku yang mereka baca.
* Rating rendah (seperti 1, 2, dan 3) sangat jarang diberikan, yang berarti user jarang memberikan penilaian negatif.
"""

user_activity = ratings['UserID'].value_counts().head(10)
plt.figure(figsize=(7,5))
ax = sns.barplot(x=user_activity.index, y=user_activity.values)
plt.title('Distribusi Jumlah Rating per User')
plt.xlabel('UserID')
plt.ylabel('Jumlah Rating')

# Menambahkan label jumlah di atas bar
for p in ax.patches:
    ax.annotate(str(int(p.get_height())),
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom')
plt.show()

"""Dari grafik ini diketahui bahwa user dengan ID 11676 merupakan user yang paling banyak memberikan rating buku, dengan total mencapai 8.524 rating. Posisi berikutnya diikuti oleh user dengan ID 98391 dengan total 5.802 rating.

### **File Users**
"""

# Menghitung jumlah baris dan kolom dalam DataFrame
jumlah_baris_users, jumlah_kolom_users = users.shape

print("Jumlah baris:", jumlah_baris_users)
print("Jumlah kolom:", jumlah_kolom_users)

users.head()

"""Output kode di atas memberikan informasi sebagai berikut:

* Terdapat **278.858 baris** dalam dataset.
* Terdapat **3 kolom** dalam dataset, yang terdiri dari: **User-ID**, **Location**, dan **Age**.
"""

# Mengubah nama kolom
users = users.rename(columns={
    'User-ID': 'UserID',
    'Location': 'location',
    'Age': 'age'
})
users.head()

# Melihat info file users
users.info()

"""Dari output di atas, diketahui bahwa:
* Terdapat kolom dengan **tipe data object**, yaitu **location**.
* Terdapat kolom numerik dengan **tipe data int64**, yaitu **UserID**.
* Dan kolom numerik dengan **tipe data float64**, yaitu **age**
"""

# Melihat distribusi user
users.describe()

"""Dari output di atas, diketahui bahwa **rata-rata usia pengguna** adalah **34.75 tahun**. Kemudian, jika diperhatikan pada **usia minimum dan maksimum pengguna**, yaitu **0 dan 244 tahun**, tentu tidak realistis. Oleh karena itu, akan dilakukan pengecekan lebih lanjut untuk bagian usia."""

# Jumlah user
print('Jumlah user: ', len(users.UserID.unique()))

# Jumlah lokasi
print('Jumlah lokasi: ', len(users.location.unique()))

# Data umur user
print('Data umur: ', users.age.unique())

"""Dari output di atas, diketahui bahwa:
* Terdapat total **278.858 user**.
* Terdapat total **57.339 lokasi** berbeda yang tercatat dari user, yang berarti user yang memberikan rating berasal dari berbagai tempat yang berbeda.
* Banyak terdapat anomali atau usia yang tidak realistis pada dataset ini, terlihat dari usia pelanggan yang berada dibawah 10 tahun atau diatas 100 tahun, dsb.
"""

# Memeriksa duplikasi
print("Jumlah duplikasi pada users: ", users.duplicated().sum())

# Menghitung jumlah user per lokasi
location_counts = users['location'].value_counts().head(10)

# Visualisasi
plt.figure(figsize=(7,5))
sns.barplot(y=location_counts.index, x=location_counts.values)
plt.title('Lokasi dengan Jumlah User Terbanyak')
plt.xlabel('Jumlah User')
plt.ylabel('Lokasi')
plt.show()

"""Dari grafik tersebut, diketahui bahwa:
* London menempati posisi teratas dengan jumlah user paling banyak, yang kemudian diikuti oleh Toronto dan Sydney.
* Kota‑kota dari Amerika Utara (AS dan Kanada) mendominasi daftar secara jumlah lokasi.

## **Data Preprocessing**

### **File Books**
"""

# Mengecek missing value pada file books
print(books.isna().sum())

"""Berdasarkan hasil output tersebut, diketahui bahwa terdapat 3 fitur yang memiliki missing value, yaitu kolom **book_author**, **publisher**, dan **image-url-l**."""

# Mengecek baris yang memiliki missing value
books[books.isnull().any(axis=1)]

"""Dari output di atas, diketahui bahwa ISBN dengan nomor **078946697X**, **2070426769**, dan **0789466953** mengalami **missalignment kolom**, dimana nilai book_author diisi dengan nilai dari year, dan seterusnya."""

# Mengatasi missalignment kolom
def fix_row(row):
    if str(row['book_author']).isdigit():
        # Menggeser nilai ke kolom yang benar
        row['image_url_l'] = row['image_url_m']
        row['image_url_m'] = row['image_url_s']
        row['image_url_s'] = row['publisher']
        row['publisher'] = row['year']
        row['year'] = int(row['book_author'])
        row['book_author'] = np.nan
    return row

books = books.apply(fix_row, axis=1)

# Mengecek missing value pada file books
print(books.isna().sum())

# Mengecek baris yang memiliki missing value
books[books.isnull().any(axis=1)]

"""Dari output di atas, terlihat bahwa missalignment kolom sudah ditangani. Namun, karena untuk modeling yang akan digunakan adalah kolom **ISBN**, **book_title**, dan **book_author**, maka kolom tersebut yang mengandung nilai NaN akan dihapus dan kolom lain yang memiliki nilai NaN akan dibiarkan."""

# Memilih ISBN tertentu
isbn_list = ["0751352497", "9627982032", "078946697X", "2070426769", "0789466953"]

# Memilih hanya beberapa kolom yang ingin ditampilkan
selected_col = ["ISBN", "book_title", "book_author", "year", "publisher"]

# Menampilkan kolom teks secara penuh
pd.set_option('display.max_colwidth', None)

# Menampilkan data
books.loc[books["ISBN"].isin(isbn_list), selected_col]

"""Dari output tersebut, diketahui bahwa book_author dari ISBN dengan nomor **078946697X**, **2070426769**, dan **0789466953** salah diisi di kolom book_title. Oleh karena itu, akan dilakukan perbaikan untuk baris tersebut."""

# ISBN dengan no. '078946697X'
books.loc[books.ISBN == '078946697X','book_author'] = "Michael Teitelbaum"
books.loc[books.ISBN == '078946697X','book_title'] = (
    "DK Readers: Creating the X-Men, How It All Began (Level 4: Proficient Readers)"
)

# ISBN dengan no. '2070426769'
books.loc[books.ISBN == '2070426769','book_author'] = "Jean-Marie Gustave Le ClÃ?Â©zio"
books.loc[books.ISBN == '2070426769','book_title'] = "Peuple du ciel, suivi de 'Les Bergers"

# ISBN dengan no. '0789466953'
books.loc[books.ISBN == '0789466953','book_author'] = "James Buckley"
books.loc[books.ISBN == '0789466953','book_title'] = (
    "DK Readers: Creating the X-Men, How Comic Books Come to Life (Level 4: Proficient Readers)"
)

# Menghapus baris yang kolom 'book_author' bernilai NaN
books_clean = books.dropna(subset=['book_author'])

# Mengecek missing value pada file books
print(books_clean.isna().sum())

"""### **File Ratings**"""

# Mengecek missing value pada file ratings
print(ratings.isna().sum())

# Menghitung jumlah rating per user
user_rating_counts = ratings['UserID'].value_counts()

# Membuat mask untuk user aktif
active_users_mask = user_rating_counts > 200

# Mengambil daftar user aktif
active_users = active_users_mask[active_users_mask].index
active_users.shape

# Memfilter dataset rating hanya untuk user aktif
ratings = ratings[ratings['UserID'].isin(active_users)]
ratings.shape

"""### **File Users**"""

# Mengecek missing value pada file users
print(users.isna().sum())

"""Berdasarkan output di atas, diketahui bahwa kolom Age memiliki **missing value**, dengan total mencapai **110.762 data**. Karena kolom ini tidak akan digunakan dalam membangun model dan juga memiliki nilai yang tidak realisitis seperti yang telah dijelaskan sebelumnya, maka kolom ini akan dihapus."""

# Menghapus kolom
users_clean = users.drop('age', axis=1)

# Mengecek informasi pada file users
print(users_clean.info())

# Memilih kolom 'ISBN', 'book_author', dan 'book_title' dari file books
books_selected = books_clean[['ISBN', 'book_title', 'book_author']]
print(type(books_selected))

# Menampilkan kolom teks secara penuh
pd.set_option('display.max_colwidth', None)

# Menggabungkan file rating dengan book_selected berdasarkan nilai ISBN
book_final = pd.merge(ratings, books_selected, on='ISBN', how='inner')
book_final.head()

# Memeriksa duplikasi
print("Jumlah duplikasi: ", book_final.duplicated().sum())

# Mengecek missing value
print(book_final.isnull().sum())

# Visualisasi buku yang paling banyak dirating
book_popularity = book_final['book_title'].value_counts().head(10)

plt.figure(figsize=(7,4))
sns.barplot(y=book_popularity.index, x=book_popularity.values)
plt.title('Distribusi Jumlah Rating per Buku')
plt.xlabel('Jumlah Rating')
plt.ylabel('Judul Buku')
plt.xticks()
plt.show()

"""Dari grafik tersebut, diketahui bahwa Buku Bridget Jones's Diary menempati posisi teratas dengan jumlah rating tertinggi, dengan total lebih dari 30 rating. Kemudian diikuti oleh 3 buku dari seri Harry Potter (Book 2, 3, dan 4), dengan total sekitar 25 rating.

"""

# Visualisasikan penulis dengan buku yang paling banyak dirating
author_popularity = book_final['book_author'].value_counts().head(10)

plt.figure(figsize=(7,5))
sns.barplot(x=author_popularity.index, y=author_popularity.values)
plt.title('Distribusi Rating Berdasarkan Penulis')
plt.xlabel('Penulis')
plt.ylabel('Jumlah Rating')
plt.xticks(rotation=45)
plt.show()

"""Dari grafik tersebut, diketahui bahwa Buku yang ditulis oleh Stephen King menjadi buku yang paling banyak diberi rating, dengan total mencapai lebih dari 700 rating."""

# Mengubah UserID menjadi list tanpa nilai yang sama
user_ids = book_final['UserID'].unique().tolist()
print('list userID: ', user_ids)

# Melakukan encoding userID
user_to_user_encoded = {x: i for i, x in enumerate(user_ids)}
print('encoded userID : ', user_to_user_encoded)

# Melakukan proses encoding angka ke ke userID
user_encoded_to_user = {i: x for i, x in enumerate(user_ids)}
print('encoded angka ke userID: ', user_encoded_to_user)

# Mengubah ISBN menjadi list tanpa nilai yang sama
book_ids = book_final['ISBN'].unique().tolist()
print('list ISBN: ', book_ids)

# Melakukan proses encoding ISBN
book_to_book_encoded = {x: i for i, x in enumerate(book_ids)}
print('encoded ISBN : ', book_to_book_encoded)

# Melakukan proses encoding angka ke ISBN
book_encoded_to_book = {i: x for i, x in enumerate(book_ids)}
print('encoded ISBN : ', book_encoded_to_book)

# Mapping UserID ke dataframe user
book_final['user'] = book_final['UserID'].map(user_to_user_encoded)

# Mapping ISBN ke dataframe book
book_final['book'] = book_final['ISBN'].map(book_to_book_encoded)

# Mendapatkan jumlah user
num_users = len(user_to_user_encoded)
print(num_users)

# Mendapatkan jumlah buku
num_books = len(book_encoded_to_book)
print(num_books)

# Mengubah rating menjadi nilai float
book_final['book_rating'] = book_final['book_rating'].values.astype(np.float32)

# Nilai minimum rating
min_rating = min(book_final['book_rating'])

# Nilai maksimal rating
max_rating = max(book_final['book_rating'])

print('Number of User: {}, Number of Book: {}, Min Rating: {}, Max Rating: {}'.format(
    num_users, num_books, min_rating, max_rating))

"""**Membagi Dataset menjadi Data Training dan Validasi**"""

# Mengacak dataset
dataset = book_final.sample(frac=1, random_state=42)
dataset.head()

# Membuat variabel x untuk mencocokkan data user dan buku menjadi satu value
x = dataset[['user', 'book']].values

# Membuat variabel y untuk membuat rating dari hasil
y = dataset['book_rating'].apply(lambda x: (x - min_rating) / (max_rating - min_rating)).values

# Membagi menjadi 80% data train dan 20% data validasi
train_indices = int(0.8 * dataset.shape[0])
x_train, x_val, y_train, y_val = (x[:train_indices],
                                  x[train_indices:],
                                  y[:train_indices],
                                  y[train_indices:])

print(x, y)

"""## **Training Model**"""

class RecommenderNet(tf.keras.Model):

  # Insialisasi fungsi
  def __init__(self, num_users, num_books, embedding_size, **kwargs):
    super(RecommenderNet, self).__init__(**kwargs)
    self.num_users = num_users
    self.num_books = num_books
    self.embedding_size = embedding_size
    self.user_embedding = layers.Embedding( # layer embedding user
        num_users,
        embedding_size,
        embeddings_initializer = 'he_normal',
        embeddings_regularizer = keras.regularizers.l2(1e-6)
    )
    self.user_bias = layers.Embedding(num_users, 1) # layer embedding user bias
    self.book_embedding = layers.Embedding( # layer embeddings book
        num_books,
        embedding_size,
        embeddings_initializer = 'he_normal',
        embeddings_regularizer = keras.regularizers.l2(1e-6)
    )
    self.book_bias = layers.Embedding(num_books, 1) # layer embedding book bias

  def call(self, inputs):
    user_vector = self.user_embedding(inputs[:,0]) # memanggil layer embedding 1
    user_bias = self.user_bias(inputs[:, 0]) # memanggil layer embedding 2
    book_vector = self.book_embedding(inputs[:, 1]) # memanggil layer embedding 3
    book_bias = self.book_bias(inputs[:, 1]) # memanggil layer embedding 4

    dot_user_book = tf.tensordot(user_vector, book_vector, 2)

    x = dot_user_book + user_bias + book_bias

    return tf.nn.sigmoid(x) # activation sigmoid

# Inisialisasi model
model = RecommenderNet(num_users, num_books, 50)

# Model compile
model.compile(
    loss = tf.keras.losses.MeanSquaredError(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=[tf.keras.metrics.RootMeanSquaredError()]
)

# Memulai training
history = model.fit(x = x_train,
                    y = y_train,
                    batch_size = 8,
                    epochs = 15,
                    validation_data = (x_val, y_val))

# Menampilkan visualisasi metrik
plt.plot(history.history['root_mean_squared_error'])
plt.plot(history.history['val_root_mean_squared_error'])
plt.title('model_metrics')
plt.ylabel('root_mean_squared_error')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper right')
plt.show()

book_df = books_selected
df = book_final

# Mengambil sample user
user_id = df['UserID'].sample(1).iloc[0]
book_read_by_user = df[df['UserID'] == user_id]

# Operator bitwise (~)
book_not_read = book_df[~book_df['ISBN'].isin(book_read_by_user.ISBN.values)]['ISBN']
book_not_read = list(
    set(book_not_read)
    .intersection(set(book_to_book_encoded.keys()))
)

book_not_read = [[book_to_book_encoded.get(x)] for x in book_not_read]
user_encoder = user_to_user_encoded.get(user_id)
user_book_array = np.hstack(
    ([[user_encoder]] * len(book_not_read), book_not_read)
)

ratings = model.predict(user_book_array).flatten()

top_ratings_indices = ratings.argsort()[-10:][::-1]
recommended_book_ids = [
    book_encoded_to_book.get(book_not_read[x][0]) for x in top_ratings_indices
]

# Mengambil skor sesuai urutan Top-10
recommended_scores = ratings[top_ratings_indices]

print('Rekomendasi Buku untuk User dengan ID: {}'.format(user_id))
print('===' * 20)
print('Buku dengan Rating Tertinggi dari User')
print('----' * 15)

top_book_user = (
    book_read_by_user.sort_values(
        by = 'book_rating',
        ascending=False
    )
    .head(5)
    .ISBN.values
)

book_df_rows = book_df[book_df['ISBN'].isin(top_book_user)]
for row in book_df_rows.itertuples():
    print('* Judul Buku  :', row.book_title)
    print('  Penulis     :', row.book_author)

print('----' * 15)
print('Rekomendasi 10 Buku Terbaik')
print('----' * 15)

recommended_book = book_df[book_df['ISBN'].isin(recommended_book_ids)].copy()
recommended_book["score"] = recommended_scores

for row in recommended_book.itertuples():
    print('* Judul Buku   :', row.book_title)
    print('  Penulis      :', row.book_author)
    print('  Skor Prediksi:', round(row.score, 4))

tf.keras.backend.clear_session()